# Generated by Django 4.0.5 on 2022-06-08 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neuralnetwork', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imgupload',
            name='file',
            field=models.ImageField(upload_to='imagenes'),
        ),
    ]
